export const solfegeSharpName = ["Do", "Di", "Re", "Ri", "Mi", "Fa", "Fi", "So", "Si", "La", "Li", "Ti"];
export const solfegeFlatName = ["Do", "Ra", "Re", "Me", "Mi", "Fa", "Se", "So", "Le", "La", "Te", "Ti"];
export const englishSharpName = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
export const englishFlatName = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"];
export const numberSharpName = ["1", "#1", "2", "#2", "3", "4", "#4", "5", "#5", "6", "#6", "7"];
export const numberFlatName = ["1", "b1", "2", "b3", "3", "4", "b5", "5", "b6", "6", "b7", "7"];
export const keyName = ["C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab", "A", "A#/Bb", "B"];
export const accidentalsType = {sharp: "sharp", flat: "flat"};
export const noteType = {solfege: "solfege", english: "english", number: "number"};
